name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - name: Build
        run: npm install && npx vite build
        working-directory: demo
        env:
          NODE_ENV: production

      - name: Deploy
        uses: denoland/deployctl@v1
        with:
          project: sveltekit-adapter-deno
          import-map: import_map.json
          entrypoint: mod.ts
          root: demo/build
